### PR TITLE
fix: firefox lyrics scrollbar

### LINKED ISSUE #966: 火狐浏览器下,全屏展示会出现滚动条,而edge不会出现
_网页端
火狐浏览器最新版_

图片

### PR DESCRIPTION
**Pull request by memorydream**
close #966

### CODE REVIEW

File: src/views/lyrics.vue [hunk 1]
```diff
@@ -641,6 +641,7 @@ export default {
     max-width: 460px;
     overflow-y: auto;
     transition: 0.5s;
+    scrollbar-width: none; //fire fox
```
Comment (pan93412) [inline src/views/lyrics.vue:644]: add the space between `//` and `fire`, and remove the space between `fire` and `fox`.

**Review by pan93412 — APPROVED** [review]
